// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://auluvtebfuuscavljlgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1bHV2dGViZnV1c2NhdmxqbGdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyNzMzNzYsImV4cCI6MjA1MTg0OTM3Nn0.Et5O3RRQttyjZfcW7yYGWEi_tpQvQx_F-cEkFAO5gFA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);